import type { HomePreset, HomePresetName } from '../lib/home-cards.ts';

// Each card occupies one rectangle; wide columns stack independently without gaps.
export const homePresets = {
    default: {
        compact: {
            minWidth: 0,
            rowHeight: 112,
            gap: 16,
            areas: [
                'author author',
                'author author',
                'author author',
                'author author',
                'stats stats',
                'stats stats',
                'stats stats',
                'heatmap heatmap',
                'heatmap heatmap',
                'categories categories',
                'categories categories',
                'tags tags',
                'tags tags',
                'recent recent',
                'recent recent',
                'recent recent',
                'recent recent',
                'popular popular',
                'popular popular',
                'popular popular',
                'popular popular',
                'moments moments',
                'moments moments',
                'moments moments',
                'projects projects',
                'projects projects',
                'projects projects',
                'links links',
                'links links',
                'links links',
            ],
        },
        medium: {
            minWidth: 640,
            rowHeight: 112,
            gap: 20,
            areas: [
                'author author author author',
                'author author author author',
                'author author author author',
                'author author author author',
                'heatmap heatmap stats stats',
                'heatmap heatmap stats stats',
                'heatmap heatmap stats stats',
                'categories categories tags tags',
                'categories categories tags tags',
                'recent recent recent recent',
                'recent recent recent recent',
                'recent recent recent recent',
                'recent recent recent recent',
                'recent recent recent recent',
                'recent recent recent recent',
                'popular popular popular popular',
                'popular popular popular popular',
                'popular popular popular popular',
                'popular popular popular popular',
                'popular popular popular popular',
                'popular popular popular popular',
                'moments moments moments moments',
                'moments moments moments moments',
                'moments moments moments moments',
                'projects projects projects projects',
                'projects projects projects projects',
                'projects projects projects projects',
                'links links links links',
                'links links links links',
                'links links links links',
            ],
        },
        wide: {
            minWidth: 960,
            rowHeight: 112,
            gap: 20,
            areas: [
                'author author heatmap heatmap stats stats',
                'author author heatmap heatmap stats stats',
                'author author heatmap heatmap stats stats',
                'author author recent recent recent recent',
                'categories categories recent recent recent recent',
                'categories categories recent recent recent recent',
                'categories categories recent recent recent recent',
                'tags tags recent recent recent recent',
                'tags tags popular popular popular popular',
                'tags tags popular popular popular popular',
                'moments moments popular popular popular popular',
                'moments moments popular popular popular popular',
                'moments moments popular popular popular popular',
                'projects projects links links links links',
                'projects projects links links links links',
                'projects projects links links links links',
            ],
        },
    },
} satisfies Record<HomePresetName, HomePreset>;
