export type ColorScheme = 'light' | 'dark';

// Palette classification is shared by first paint, runtime and comments.
export const themeCatalog = [
    { name: 'light', colorScheme: 'light' },
    { name: 'dark', colorScheme: 'dark' },
    { name: 'cupcake', colorScheme: 'light' },
    { name: 'bumblebee', colorScheme: 'light' },
    { name: 'emerald', colorScheme: 'light' },
    { name: 'corporate', colorScheme: 'light' },
    { name: 'synthwave', colorScheme: 'dark' },
    { name: 'retro', colorScheme: 'light' },
    { name: 'cyberpunk', colorScheme: 'dark' },
    { name: 'valentine', colorScheme: 'light' },
    { name: 'halloween', colorScheme: 'dark' },
    { name: 'garden', colorScheme: 'light' },
    { name: 'forest', colorScheme: 'dark' },
    { name: 'aqua', colorScheme: 'light' },
    { name: 'lofi', colorScheme: 'light' },
    { name: 'pastel', colorScheme: 'light' },
    { name: 'fantasy', colorScheme: 'light' },
    { name: 'wireframe', colorScheme: 'light' },
    { name: 'black', colorScheme: 'dark' },
    { name: 'luxury', colorScheme: 'dark' },
    { name: 'dracula', colorScheme: 'dark' },
    { name: 'cmyk', colorScheme: 'light' },
    { name: 'autumn', colorScheme: 'light' },
    { name: 'business', colorScheme: 'dark' },
    { name: 'acid', colorScheme: 'light' },
    { name: 'lemonade', colorScheme: 'light' },
    { name: 'night', colorScheme: 'dark' },
    { name: 'coffee', colorScheme: 'dark' },
    { name: 'winter', colorScheme: 'light' },
    { name: 'dim', colorScheme: 'dark' },
    { name: 'nord', colorScheme: 'light' },
    { name: 'sunset', colorScheme: 'dark' },
    { name: 'caramellatte', colorScheme: 'light' },
    { name: 'abyss', colorScheme: 'dark' },
    { name: 'silk', colorScheme: 'light' },
] satisfies { name: string; colorScheme: ColorScheme }[];
